### PR TITLE
Get project compiling

### PR DESCRIPTION
**Pull request by jtmcdole**
- remove hardcoded, invalid paths
- move from Makefile to ccompile for easier cross-platform compilation
- move template code in util.cc to util.h so it compiles on windows (wont link otherwise).
- re-run bindings (future plan: remove python requirement)

### CODE REVIEW

**Comment by jtmcdole** [comment]
I've got similar fixes for dart-gl coming.

**Comment by lyceel** [comment]
Any particular reason why you're checking in the DLL?

**Comment by boustrophedon** [comment]
Regarding the "remove python requirement" plan, what do you intend to replace it with? I keep wanting to rewrite the generator to use libclang and actually parse C headers properly but I've been super busy this semester and last semester and I haven't had time.

**Comment by jtmcdole** [comment]
@lyceel : no reason other than it is built. I've seen other native extensions check in the native libs for linux, windows, and mac so you can download it from pub working. I'll remove them though.

@boustrophedon : it is just parsing some .h files - I'd like to just keep everything dart centric and limit the tool requirements.

**Comment by jtmcdole** [comment]
If no one has any complaints, I'd love to commit this and move on to other things :)

**Comment by lyceel** [comment]
Merged.  Sorry, forgot about this :-)

**Pull request merged**
